apiVersion: v1
kind: Namespace
metadata:
  name: openshift-metrics
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metrics-server
  namespace: openshift-operators
spec:
  channel: stable
  name: metrics-server
  source: operatorhubio-catalog
  sourceNamespace: openshift-marketplace

